
default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons" 
    firebase_app_distribution(
    app: "1:752786945350:android:681765ee27c2e98634a147",
    firebase_cli_token:"1//09c30rJfc4MkeCgYIARAAGAkSNwF-L9IrJ8HrVWL7hNR144TlyoPwtsBM-N9QurYRj5drFfO594BdBe1UpnrBvIJ81DGvRl5w7AY",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "darshmostafa690@gmail.com",
    release_notes: "first fastlane firebase distribution"

    )
  
  end
end
